CREATE OR REPLACE PACKAGE BODY HOTEL IS
    FUNCTION IS_RESERVATION_VALID(
        ARG_ROOM_NUMBER NUMBER,
        ARG_START_DATE DATE,
        ARG_END_DATE DATE
    ) RETURN BOOLEAN AS  
    BEGIN
        FOR RESERVATION IN (SELECT RESERVATION_ID, START_DATE, END_DATE FROM RESERVATIONS WHERE ROOM_NUMBER = ARG_ROOM_NUMBER)
        LOOP
            IF(NOT(ARG_START_DATE >= RESERVATION.END_DATE AND RESERVATION.START_DATE >= ARG_END_DATE)) THEN
                RETURN FALSE;
            END IF;
        END LOOP;
        RETURN TRUE;
    END IS_RESERVATION_VALID;
    

END HOTEL;
