CREATE OR REPLACE PACKAGE HOTEL IS
    FUNCTION IS_RESERVATION_VALID(
        ARG_ROOM_NUMBER NUMBER,
        ARG_START_DATE DATE,
        ARG_END_DATE DATE
    ) RETURN BOOLEAN;
--    
--    FUNCTION CALCULATE_MONTHLY_INCOME(
--        MONTH_NUMBER NUMBER,
--        YEAR_NUMBER NUMBER
--    ) RETURN NUMBER;
--    
--    FUNCTION GET_DISCOUNT_ID(
--        CLIENT_ID NUMBER
--    ) RETURN NUMBER;
--    
--    PROCEDURE RESERVE(
--        CLIENT_ID NUMBER,
--        ROOM_TYPE NUMBER,
--        START_DATE DATE, 
--        END_DATE DATE
--    );
--    
--    PROCEDURE BUY_OFFER(
--        CLIENT_ID NUMBER,
--        OFFER_ID NUMBER,
--        START_DATE DATE,
--        END_DATE DATE
--    );
END HOTEL;