-- Pokoje z widokiem na morze/plażę
INSERT INTO ROOM_TYPES VALUES (0, 'sea', 240, 1);
INSERT INTO ROOM_TYPES VALUES (1, 'sea', 280, 2);
INSERT INTO ROOM_TYPES VALUES (2, 'sea', 320, 3);
INSERT INTO ROOM_TYPES VALUES (3, 'sea', 360, 4);

-- Pokoje z widokiem na miasteczko
INSERT INTO ROOM_TYPES VALUES (4, 'none', 200, 1);
INSERT INTO ROOM_TYPES VALUES (5, 'town', 240, 2);
INSERT INTO ROOM_TYPES VALUES (6, 'town', 280, 3);
INSERT INTO ROOM_TYPES VALUES (7, 'town', 320, 4);

-- Pokoje bez widoku
INSERT INTO ROOM_TYPES VALUES (8, 'none', 180, 1);
INSERT INTO ROOM_TYPES VALUES (9, 'none', 200, 2);
INSERT INTO ROOM_TYPES VALUES (10, 'none', 220, 3);
INSERT INTO ROOM_TYPES VALUES (11, 'none', 240, 4);
INSERT INTO ROOM_TYPES VALUES (12, 'none', 260, 5);