-- Sektory na pierwszym piętrze
INSERT INTO SECTORS (SECTOR_ID, SECTOR_LEVEL) VALUES (1, 1);
INSERT INTO SECTORS (SECTOR_ID, SECTOR_LEVEL) VALUES (2, 1);
INSERT INTO SECTORS (SECTOR_ID, SECTOR_LEVEL) VALUES (3, 1);
INSERT INTO SECTORS (SECTOR_ID, SECTOR_LEVEL) VALUES (4, 1);

-- Sektory na drugim piętrze
INSERT INTO SECTORS (SECTOR_ID, SECTOR_LEVEL) VALUES (5, 2);
INSERT INTO SECTORS (SECTOR_ID, SECTOR_LEVEL) VALUES (6, 2);
INSERT INTO SECTORS (SECTOR_ID, SECTOR_LEVEL) VALUES (7, 2);
INSERT INTO SECTORS (SECTOR_ID, SECTOR_LEVEL) VALUES (8, 2);

-- Sektory na trzecim, najwyższym, piętrze
INSERT INTO SECTORS (SECTOR_ID, SECTOR_LEVEL) VALUES (9, 3);
INSERT INTO SECTORS (SECTOR_ID, SECTOR_LEVEL) VALUES (10, 3);
INSERT INTO SECTORS (SECTOR_ID, SECTOR_LEVEL) VALUES (11, 3);
INSERT INTO SECTORS (SECTOR_ID, SECTOR_LEVEL) VALUES (12, 3);