INSERT INTO OFFERS VALUES (1, 'breakfast', 15);
INSERT INTO OFFERS VALUES (2, 'dinner', 20);
INSERT INTO OFFERS VALUES (3, 'supper', 10);

INSERT INTO OFFERS VALUES (4, 'boat-1', 90);
INSERT INTO OFFERS VALUES (5, 'boat-2', 110);
INSERT INTO OFFERS VALUES (6, 'boat-3', 150);

INSERT INTO OFFERS VALUES (7, 'motorboat-1', 80);
INSERT INTO OFFERS VALUES (8, 'motorboat-2', 100);

INSERT INTO OFFERS VALUES (9, 'bike', 20);
INSERT INTO OFFERS VALUES (10, 'mtb-bike', 25);
INSERT INTO OFFERS VALUES (11, 'kids-bike', 15);

INSERT INTO OFFERS VALUES (12, 'car', 110);
INSERT INTO OFFERS VALUES (13, 'van', 150);