DROP SEQUENCE RESERVATION_SEQ;
DROP SEQUENCE BOUGHT_OFFERS_SEQ;

DROP TABLE WORKERS;
DROP TABLE BOUGHT_OFFERS;
DROP TABLE OFFERS;
DROP TABLE RESERVATIONS;
DROP TABLE DISCOUNTS;
DROP TABLE ROOMS;
DROP TABLE SECTORS;
DROP TABLE ROOM_TYPES;
DROP TABLE CLIENTS;